language: cpp
script: 
  - cmake ./ && make -j
before_install:
  - echo "yes" | sudo apt-add-repository ppa:boost-latest/ppa
  - echo "yes" | sudo apt-add-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq boost1.54 gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
